import { Table } from 'antd';
import dateFormat from 'dateformat';

let mock = [
    {
        employeeCode: 'VinhNDQ',
        fullName: 'Nguyễn Đặng Quý Vinh',
        gender: null,
        dateOfBirt: null,
        hireDate: null,
        endDate: null,
        vissoftEmail: 'vinh12345@gmail.com',
        personalEmail: 'vinh123@gmail.com',
        phoneNumber: '0352614112',
        title: 'Nhân sự',
        department: 'Hành chính',
        managerCode: null,
        dayOff: null,
        managerName: null,
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'ThaiDD',
        fullName: 'Đỗ Đình Thái',
        gender: true,
        dateOfBirt: '1996-02-03',
        hireDate: '0022-07-11',
        endDate: '2023-02-10T00:00:00.000+0000',
        vissoftEmail: 'thaidd@vissoft.vn',
        personalEmail: 'dinhthaitn96@gmail.com',
        phoneNumber: '0969767627',
        title: 'Lập trình viên',
        department: 'DEV',
        managerCode: 'CUONGDV',
        dayOff: null,
        managerName: 'Đặng Việt Cường',
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'ANHBC1',
        fullName: 'Bui Chung Anh',
        gender: true,
        dateOfBirt: '2002-12-20',
        hireDate: '2020-09-20',
        endDate: '2023-11-29T00:00:00.000+0000',
        vissoftEmail: 'anh@vissoft.vn',
        personalEmail: 'anh@gmail.com',
        phoneNumber: '0987655432',
        title: 'Lập trình viên',
        department: 'DEV',
        managerCode: null,
        dayOff: null,
        managerName: null,
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'PHUOCDTH3',
        fullName: 'Đỗ Thị Hồng Phước',
        gender: true,
        dateOfBirt: '1999-02-01',
        hireDate: '2021-01-01',
        endDate: null,
        vissoftEmail: 'phuocdth@vissoft.vn',
        personalEmail: 'do1phuoc6219999@gmail.com',
        phoneNumber: '0829122226',
        title: 'Kiểm thử',
        department: 'Test tên phòng ban',
        managerCode: 'ANNN',
        dayOff: null,
        managerName: 'Nguyễn Ngọc An',
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'NGANN',
        fullName: 'Nga Nga Nga',
        gender: true,
        dateOfBirt: '2000-01-01',
        hireDate: '2021-03-02',
        endDate: '2025-03-02T00:00:00.000+0000',
        vissoftEmail: 'nga@vissoft.vn',
        personalEmail: 'nga@gmail.com',
        phoneNumber: '0999000000',
        title: 'Kiểm thử',
        department: 'Kho',
        managerCode: 'PHUOCDTH2',
        dayOff: null,
        managerName: 'Do Thi Hong Phuoc',
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'THANHNN',
        fullName: 'Nguyễn Nam Thành',
        gender: true,
        dateOfBirt: '2001-01-01',
        hireDate: '2021-03-31',
        endDate: '2023-03-02T00:00:00.000+0000',
        vissoftEmail: 'thanhnm@vissoft.vn',
        personalEmail: 'thanh@edu.vn',
        phoneNumber: '0945069456',
        title: 'Lập trình viên',
        department: 'DEV',
        managerCode: 'DUNGBT2',
        dayOff: null,
        managerName: 'Bui Tien Dung',
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'LUANDV2',
        fullName: 'Dương Văn Luận',
        gender: true,
        dateOfBirt: '1997-10-10',
        hireDate: '2021-10-01',
        endDate: '2023-02-28T00:00:00.000+0000',
        vissoftEmail: 'luandv@vissoft.vn',
        personalEmail: 'luandv@gmail.com',
        phoneNumber: '0984666666',
        title: 'Lập trình viên',
        department: 'DEV',
        managerCode: 'MANHTD',
        dayOff: null,
        managerName: 'Trương Đức Mạnh',
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'DTHP',
        fullName: 'Phuoc Dth',
        gender: false,
        dateOfBirt: '1999-09-06',
        hireDate: '2021-11-30',
        endDate: '2023-02-03T00:00:00.000+0000',
        vissoftEmail: 'vissoft@vissoft.vn',
        personalEmail: 'user@gmail.com',
        phoneNumber: '0918239128',
        title: 'Kiểm thử',
        department: 'BODL',
        managerCode: 'TESTDTHP',
        dayOff: null,
        managerName: 'đê tê hắt phước test',
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'TESTNT1',
        fullName: 'Nguyễn Thảo Test',
        gender: false,
        dateOfBirt: '2000-01-01',
        hireDate: '2021-12-01',
        endDate: null,
        vissoftEmail: 'thao@vissoft.vn',
        personalEmail: 'nguyenbichthao15102000@gmail.com',
        phoneNumber: '0378480640',
        title: 'Chủ sở hữu sản phẩm',
        department: 'Lập trình viên',
        managerCode: 'LUANDV3',
        dayOff: null,
        managerName: 'Dương Văn Luận',
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'HDPTP',
        fullName: 'Pê Tê Phương Hđ',
        gender: true,
        dateOfBirt: '1998-12-21',
        hireDate: '2021-12-06',
        endDate: null,
        vissoftEmail: 'dung@vissoft.vn',
        personalEmail: 'phuongpt@gmail.com',
        phoneNumber: '0123456789',
        title: 'Kiểm thử',
        department: 'BODL',
        managerCode: 'PHUONGNT7',
        dayOff: null,
        managerName: 'Nờ tê Phương',
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'PHUONGPT1',
        fullName: 'Pê Tê Phương',
        gender: true,
        dateOfBirt: '1998-12-21',
        hireDate: '2021-12-06',
        endDate: null,
        vissoftEmail: 'dung@vissoft.vn',
        personalEmail: 'phuongpt@gmail.com',
        phoneNumber: '0123456789',
        title: 'Kiểm thử',
        department: 'BODL',
        managerCode: 'HAINTBTH',
        dayOff: null,
        managerName: 'Nờ Tê Bê Thảo Hđ Hai',
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'THUPTP',
        fullName: 'Pê Tê Phương Thử',
        gender: false,
        dateOfBirt: '1998-12-21',
        hireDate: '2021-12-06',
        endDate: null,
        vissoftEmail: 'dung@vissoft.vn',
        personalEmail: 'a@gmail.com',
        phoneNumber: '0123456789',
        title: 'Kiểm thử',
        department: 'BODL',
        managerCode: null,
        dayOff: null,
        managerName: null,
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'MOTH',
        fullName: 'Hoàng Một',
        gender: true,
        dateOfBirt: '1998-12-21',
        hireDate: '2021-12-06',
        endDate: null,
        vissoftEmail: 'dung@vissoft.vn',
        personalEmail: 'user@gmail.com',
        phoneNumber: '0123456789',
        title: 'Kiểm thử',
        department: 'BODL',
        managerCode: null,
        dayOff: null,
        managerName: null,
        workingStatus: 'ACTIVE',
    },
    {
        employeeCode: 'HAIH',
        fullName: 'Hoàng Hai',
        gender: true,
        dateOfBirt: '1998-12-21',
        hireDate: '2021-12-06',
        endDate: '2022-02-26T00:00:00.000+0000',
        vissoftEmail: 'dung@vissoft.vn',
        personalEmail: 'dung@vissoft.vn',
        phoneNumber: '0123456789',
        title: 'Kiểm thử',
        department: 'BODL',
        managerCode: null,
        dayOff: null,
        managerName: null,
        workingStatus: 'ACTIVE',
    },
];

const Profile = () => {
    mock = mock.map((it, index) => {
        return {
            ...it,
            index: index + 1,
            gender: it.gender ? 'Nam' : 'Nữ',
            dateOfBirth: it.dateOfBirt ? dateFormat(new Date(it.dateOfBirt), 'dd-mm-yyyy') : '--',
        };
    });

    const columns = [
        {
            title: 'STT',
            dataIndex: 'index',
            key: 'index',
        },
        {
            title: 'Mã nhân viên',
            dataIndex: 'employeeCode',
            key: 'employeeCode',
        },
        {
            title: 'Tên nhân viên',
            dataIndex: 'fullName',
            key: 'fullName',
        },
        {
            title: 'Giới tính',
            dataIndex: 'gender',
            key: 'gender',
        },
        {
            title: 'Ngày sinh',
            dataIndex: 'dateOfBirth',
            key: 'dateOfBirth',
        },
    ];

    return (
        <div className='p-[24px] h-full'>
            <Table dataSource={mock} columns={columns} />
        </div>
    );
};

export default Profile;
